# Generated by Django 4.0.4 on 2022-05-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_department_rename_skill_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.AddField(
            model_name='job',
            name='job_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.company'),
        ),
    ]
