# Generated by Django 4.0.4 on 2022-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='skill',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
