# Generated by Django 4.0.4 on 2022-05-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_rename_skill_recruiter_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
    ]
